### ISSUE TITLE
How to run helloworld.foo ? 

### ISSUE THREAD

**Issue by xbee** [apkrieg/foovm#2]
How to run helloworld.foo ?

**Comment by apkrieg** [comment]
Sorry for not getting back to you sooner. There is currently no way to simply compile and/or run a file. You will have to translate the code to bytecode by hand and insert it into the `vm.Heap`. Then call `vm.Exec()`. See [here](https://github.com/apkrieg/foovm/blob/master/main/main.go) for an example of how to do this.
